openapi: 3.1.0

info:
  title: Go DDD
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: User

paths:
  /users:
    post:
      tags:
        - User
      summary: Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: 'example@example.com'
                password: 'password'
                password_confirm: 'password'
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /users/login:
    post:
      tags:
        - User
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                session: false
                email: 'example@example.com'
                password: 'password'
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /users/refresh-token:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: RefreshToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                session: false
                refresh_token: ''
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /users/reset-password-request:
    patch:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: ResetPasswordRequest
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: 'example@example.com'
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /users/reset-password:
    patch:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: ResetPassword
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                recovery_token: ''
                password: 'password'
                password_confirm: 'password'
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /users/me:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: Me
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /health:
    get:
      tags:
        - default
      summary: Health
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
